version: '3.2'

services:
  aws-multi-account-test-api:
    image: aws-multi-account-test-api
    build:
      context: aws-multi-account-test-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000


  aws-multi-account-test-api-test:
    image: aws-multi-account-test-api-test
    build:
      context: .
      dockerfile: aws-multi-account-test-api.Tests/Dockerfile
